USE [B_DB14_2018]
GO
CREATE PROC spResetRelations AS
BEGIN
DROP TABLE IF EXISTS AFTALE
DROP TABLE IF EXISTS PATIENT_PAAROERENDE
DROP TABLE IF EXISTS PATIENT
DROP TABLE IF EXISTS LAEGE
DROP TABLE IF EXISTS PAAROERENDE
DROP TABLE IF EXISTS PERSON
DROP TABLE IF EXISTS KLINIK
DROP TABLE IF EXISTS ADRESSE

CREATE TABLE ADRESSE
(
	AdresseId			INT		  		NOT NULL IDENTITY(1,1),
	Gade				VARCHAR(MAX)	NOT NULL,
	HusNummer			VARCHAR(MAX)	NOT NULL,
	PostNummer			VARCHAR(MAX)	NOT NULL,
	Boby				VARCHAR(MAX)	NOT NULL,
	CONSTRAINT			ADRESSE_PK		PRIMARY KEY(AdresseId)
)

CREATE TABLE KLINIK
(
	KlinikId 			INT				NOT NULL IDENTITY(1,1),
	Navn 				VARCHAR(MAX) 	NOT NULL,
	AdresseId			INT 			NOT NULL,
	CONSTRAINT			KLINIK_PK 		PRIMARY KEY(KlinikId),
	CONSTRAINT			ADRESSE_FK		FOREIGN KEY(AdresseId)
  			REFERENCES	ADRESSE(AdresseId)
)

CREATE TABLE PERSON
(
	PersonID			INT				NOT NULL IDENTITY(1,1),
	Navn				VARCHAR(MAX)	NOT NULL,
	HjemAdresseId		INT				NOT NULL,
	ArbejdsAdresseId	INT				NOT NULL,
	CONSTRAINT			PERSONID_PK		PRIMARY KEY(PersonId),
	CONSTRAINT			HJEMADRESSEID_FK FOREIGN KEY (HjemAdresseId)
  				REFERENCES ADRESSE(AdresseId)
		  			ON DELETE NO ACTION,
	CONSTRAINT			ARBEJDSADRESSEID_FK FOREIGN KEY (ArbejdsAdresseId)
  				REFERENCES ADRESSE(AdresseId)
)

CREATE TABLE LAEGE
(
	LaegeId				INT				NOT NULL IDENTITY(1,1),
	KlinikId			INT				NOT NULL,
	Loenramme			VARCHAR(1)		NOT NULL,
	TimeLoen			FLOAT			NOT NULL,
	PersonId			INT				NOT NULL,
	CONSTRAINT			LAEGE_PK	PRIMARY KEY(LaegeId),
	CONSTRAINT			KLINIKID_FK FOREIGN KEY(KlinikId)
  				REFERENCES KLINIK(KlinikId),
  CONSTRAINT			LAEGEID_FK FOREIGN KEY(PersonId)
  				REFERENCES PERSON(PersonId)
)

CREATE TABLE PATIENT
(
	PatientId			INT				NOT NULL IDENTITY(1,1),
	PersonId			INT				NOT NULL,
	CONSTRAINT			PATIENT_PK		PRIMARY KEY(PatientId),
	CONSTRAINT			PATIENT_FK		FOREIGN KEY(PersonId)
  				REFERENCES PERSON(PersonId)
)

CREATE TABLE PAAROERENDE
(
	PersonId			INT				NOT NULL,
	CONSTRAINT			PAAROERENDE_PK	PRIMARY KEY(PersonId),
	CONSTRAINT			PAAROERENDE_FK	FOREIGN KEY(PersonId)
  				REFERENCES PERSON(PersonId)
)

CREATE TABLE PATIENT_PAAROERENDE
(
	PatientId			INT				NOT NULL,
	PersonId			INT				NOT NULL,
	CONSTRAINT			PATIENTID_PERSONID_PK	PRIMARY KEY(PatientId, PersonId),
	CONSTRAINT			PERSONID_FK				FOREIGN KEY(PersonId)
  				REFERENCES PERSON(PersonId),
	CONSTRAINT			PATIENTID_FK	FOREIGN KEY(PatientId)
  				REFERENCES PATIENT(PatientId)
)

CREATE TABLE AFTALE
(
	AftaleId			INT				NOT NULL IDENTITY(1,1),
	LaegeId				INT				NOT NULL,
	Klinik				INT				NOT NULL,
	Patient				INT				NOT NULL,
	Dato				DATETIME2 		NOT NULL,
	Tid					VARCHAR(MAX)	NOT NULL,
	CONSTRAINT			AFTALE_PK		PRIMARY KEY(AftaleId),
	CONSTRAINT			AFTALE_LAEGE_FK	FOREIGN KEY(LaegeId)
  				REFERENCES LAEGE(LaegeId),
	CONSTRAINT			KLINIK_FK		FOREIGN KEY(Klinik)
  				REFERENCES KLINIK(KlinikId),
	CONSTRAINT			AFTALE_PATIENT_FK FOREIGN KEY(Patient)
  				REFERENCES PATIENT(PatientId)
)
END